### ISSUE TITLE
Attribute datatypes

### ISSUE THREAD

**Issue by madhu-kt** [arun1729/cog#27]
This is an awesome library. 

I just started digging into this, but are there plans to support additional types (other than strings)? It would allow us to extend functionality with more extensive querying, such as getting all nodes with a `score` attribute greater than `x`, etc.

Thanks!

**Comment by arun1729** [comment]
Thanks! Yes, supporting a numeric type is part of the roadmap. The next two releases will be focused on improved storage and performance. The next release (3.0.0, coming out soon) will contain major changes to storage and indexing which will provide significant performance improvement and ability to handle larger datasets. The subsequent release will be focused on caching but could potentially contain new features.
