### ISSUE TITLE
Installation of CogDB fails due to dependency on old xxhash version

### ISSUE THREAD

**Issue by k-tod** [arun1729/cog#40]
While attempting to install CogDB on a Win11 machine with Python 3.10.1 and pip 22.3.1 I observed that the installation fails due to dependency on old xxhash version:
![image](https://user-images.githubusercontent.com/32603366/211147427-e297a5fd-f05d-423d-b95e-963d0ac6dada.png)

Would it be possible to update the CogDB project to use a more recent version of xxhash library, that doesn't require installation of Microsoft C++ Build Tools?

**Comment by arun1729** [comment]
I upgraded CogDB (3.0.4) to use `xxhash` `3.2.0` (latest). If you do a pip install now, you should be able to install CogDB 3.0.4 that uses the latest xxhash. Hope it helps.

**Comment by k-tod** [comment]
Now it works like a charm, thank you very much !
