### ISSUE TITLE
Delete all nodes and relationships

### ISSUE THREAD

**Issue by Anjaligk1990** [arun1729/cog#43]
Is there any way in Cogdb to delete all the created nodes and relationships. This is for an automation testing setup

**Comment by arun1729** [comment]
Not currently, you will have to delete the directory where the graph lives and recreate the graph.

**Comment by Anjaligk1990** [comment]
> Not currently, you will have to delete the directory where the graph lives and recreate the graph.

Thanks for the quick response. We can utilise this option
